name: Node CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@action-summary
        with:
          TOOLCHAIN: respeca
          VALIDATE_LINKS: false
          VALIDATE_PUBRULES: false
          GH_PAGES_BRANCH: gh-pages
          W3C_API_KEY: ${{ secrets.W3C_API_KEY }}
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-device-apis/2021May/0008.html"
          W3C_NOTIFICATIONS_CC: "${{ secrets.CC }}"
          W3C_BUILD_OVERRIDE: |
            specStatus: CRD
